{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sherman-qc.fullname" . }}-backend
  labels:
    {{- include "sherman-qc.backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "sherman-qc.backend.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sherman-qc.fullname" . }}-frontend
  labels:
    {{- include "sherman-qc.frontend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "sherman-qc.frontend.selectorLabels" . | nindent 6 }}
{{- if .Values.worker.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sherman-qc.fullname" . }}-worker
  labels:
    {{- include "sherman-qc.worker.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "sherman-qc.worker.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
