{{- if not .Values.externalPostgresql.existingSecret }}
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sherman-qc.fullname" . }}-postgresql
  labels:
    {{- include "sherman-qc.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.auth.password | required "postgresql.auth.password is required" | quote }}
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | default .Values.postgresql.auth.password | quote }}
{{- end }}
{{- end }}
---
{{- if not .Values.externalRedis.existingSecret }}
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sherman-qc.fullname" . }}-redis
  labels:
    {{- include "sherman-qc.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.auth.password | required "redis.auth.password is required" | quote }}
{{- end }}
{{- end }}
---
{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.auth.jwtSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.jwtSecret.name }}
  labels:
    {{- include "sherman-qc.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.auth.jwtSecret.key }}: {{ randAlphaNum 64 | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ai.anthropicApiKeySecret.name }}
  labels:
    {{- include "sherman-qc.labels" . | nindent 4 }}
type: Opaque
data: {}
